Algoritmo "programa_salario"

Var
// Crie um programa que leia o número de dias trabalhados em um mês e mostre o
// salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha
// R$25 por hora trabalhada.
  dias_trabalhados, dia, salario: real

Inicio
ESCREVAL ("Informe a quantidade de dias trabalhados no mês de Outubro")
LEIA (dias_trabalhados)
dia <- 8*25
salario <- dia*dias_trabalhados)
ESCREVA ( "O salário do mês de Outubro é", salario)



Fimalgoritmo